/**
 * Noms francais des armes principales, par cle stat.ink.
 *
 * Table figee dans le depot plutot que jointe a l'execution : les noms
 * francais viennent de sendou.ink (`locales/fr-EU/weapons.json`), qui les
 * indexe par identifiant numerique interne, tandis que stat.ink designe les
 * armes par une cle texte et ne range cet identifiant que dans ses `aliases`.
 * Faire la jointure une fois ici evite d'en dependre a chaque compte rendu.
 *
 * Seules les armes dont le nom francais differe de l'anglais figurent ici :
 * les autres (Nautilus 47, Nautilus 79) retombent correctement sur l'anglais.
 *
 * Regenerer apres une mise a jour du jeu :
 *   stat.ink   https://stat.ink/api/v3/weapon          (cle + aliases)
 *   sendou.ink locales/fr-EU/weapons.json              (MAIN_<identifiant>)
 */
const ARMES: Record<string, string> = {
  "52gal": "Calibre 2000",
  "52gal_deco": "Calibre 2000 chic",
  "96gal": "Calibre 3000",
  "96gal_deco": "Calibre 3000 chic",
  "96gal_sou": "Calibre 3000 guépapex",
  bold: "Marqueur lourd",
  bold_neo: "Marqueur lourd Néo",
  bottlegeyser: "Compresseur",
  bottlegeyser_foil: "Compresseur alu",
  heroshooter_replica: "Lanceur héroïque (réplique)",
  jetsweeper: "Nettoyeur XL",
  jetsweeper_cobr: "Nettoyeur XL COB-R",
  jetsweeper_custom: "Nettoyeur XL modifié",
  momiji: "Liquidateur Sr.",
  nzap85: "N-ZAP 85",
  nzap89: "N-ZAP 89",
  octoshooter_replica: "Lanceur Octaling (réplique)",
  order_shooter_replica: "Lanceur d'Ordre (réplique)",
  petshooter_replica: "Liquidateur soda (réplique)",
  prime: "Liquidateur pro",
  prime_collabo: "Liquidateur pro griffé",
  prime_frzn: "Liquidateur pro GLA-C",
  promodeler_mg: "Aérogun",
  promodeler_rg: "Aérogun premium",
  promodeler_sai: "Aérogun chromapex",
  sharp: "Marqueur léger",
  sharp_geck: "Marqueur léger G-KO",
  sharp_neo: "Marqueur léger Néo",
  spaceshooter: "Lanceur spatial",
  spaceshooter_collabo: "Lanceur spatial Aroz",
  sshooter: "Liquidateur",
  sshooter_collabo: "Liquidateur griffé",
  sshooter_kou: "Liquidateur glamapex",
  wakaba: "Liquidateur Jr.",
  clashblaster: "Rafablaster",
  clashblaster_neo: "Rafablaster Néo",
  hotblaster: "Éclablaster",
  hotblaster_custom: "Éclablaster modifié",
  hotblaster_en: "Éclablaster mirapex",
  longblaster: "Éclablaster XL",
  longblaster_custom: "Éclablaster XL griffé",
  nova: "Proxiblaster",
  nova_neo: "Proxiblaster Néo",
  order_blaster_replica: "Blaster d'Ordre (réplique)",
  rapid: "Turboblaster",
  rapid_deco: "Turboblaster chic",
  rapid_elite: "Turboblaster pro",
  rapid_elite_deco: "Turboblaster pro chic",
  rapid_elite_wntr: "Turboblaster pro POL-R",
  sblast91: "S-Blaster '91",
  sblast92: "S-Blaster '92",
  h3reelgun: "Arroseur lourd",
  h3reelgun_d: "Arroseur lourd Cétacé",
  h3reelgun_snak: "Arroseur lourd VIP-R",
  l3reelgun: "Arroseur léger",
  l3reelgun_d: "Arroseur léger Cétacé",
  l3reelgun_haku: "Arroseur léger éclapex",
  dualsweeper: "Double nettoyeur",
  dualsweeper_custom: "Double nettoyeur modifié",
  dualsweeper_tei: "Double nettoyeur zébrapex",
  gaen_ff: "Double ignifugeur",
  gaen_ff_custom: "Double ignifugeur modifié",
  kelvin525: "Double Kelvin 525",
  kelvin525_deco: "Double Kelvin 525 chic",
  maneuver: "Double encreur",
  maneuver_collabo: "Double encreur griffé",
  maneuver_you: "Double encreur flambapex",
  order_maneuver_replica: "Arme double d'Ordre (réplique)",
  quadhopper_black: "Double voltigeur noir",
  quadhopper_white: "Double voltigeur blanc",
  sputtery: "Double moucheteur",
  sputtery_hue: "Double moucheteur nuancé",
  sputtery_owl: "Double moucheteur NOC-T",
  carbon: "Rouleau carbone",
  carbon_angl: "Rouleau carbone BOD-RWA",
  carbon_deco: "Rouleau carbone chic",
  dynamo: "Dynamo-rouleau",
  dynamo_mei: "Dynamo-rouleau galapex",
  dynamo_tesla: "Dynamo-rouleau tesla",
  order_roller_replica: "Rouleau d'Ordre (réplique)",
  splatroller: "Rouleau",
  splatroller_collabo: "Rouleau griffé",
  variableroller: "Flexi-rouleau",
  variableroller_foil: "Flexi-rouleau alu",
  wideroller: "Rouleau large",
  wideroller_collabo: "Rouleau large Xpress",
  wideroller_waku: "Rouleau large astrapex",
  fincent: "Épinceau écaïe",
  fincent_brnz: "Épinceau écaïe BRN-Z",
  fincent_hue: "Épinceau écaïe nuancé",
  hokusai: "Épinceau brosse",
  hokusai_hue: "Épinceau brosse nuancé",
  hokusai_sui: "Épinceau brosse stellapex",
  order_brush_replica: "Pinceau d'Ordre (réplique)",
  pablo: "Épinceau",
  pablo_hue: "Épinceau nuancé",
  dentalwiper_mint: "Sabrifrice menthe",
  dentalwiper_sumi: "Sabrifrice charbon",
  drivewiper: "Éclatana Doto",
  drivewiper_deco: "Éclatana Doto chic",
  drivewiper_rust: "Éclatana Doto OXY-D",
  jimuwiper: "Éclatana d'estampe",
  jimuwiper_fuu: "Éclatana d'estampe décapex",
  jimuwiper_hue: "Éclatana d'estampe nuancé",
  order_wiper_replica: "Éclatana d'Ordre (réplique)",
  bamboo14mk1: "Bimbamboum Mk I",
  bamboo14mk2: "Bimbamboum Mk II",
  liter4k: "Extraceur +",
  liter4k_custom: "Extraceur + modifié",
  liter4k_scope: "Extraceur + zoom",
  liter4k_scope_custom: "Extraceur + zoom modifié",
  order_charger_replica: "Fusil d'Ordre (réplique)",
  rpen_5b: "Crayon X - 5B",
  rpen_5h: "Crayon X - 5H",
  soytuber: "Détubeur",
  soytuber_custom: "Détubeur modifié",
  splatcharger: "Concentraceur",
  splatcharger_collabo: "Concentraceur E+F",
  splatcharger_frst: "Concentraceur CAM-O",
  splatscope: "Concentraceur zoom",
  splatscope_collabo: "Concentraceur zoom E+F",
  splatscope_frst: "Concentraceur zoom CAM-O",
  squiclean_a: "Décap'express Alpha",
  squiclean_b: "Décap'express Bêta",
  bucketslosher: "Seauceur",
  bucketslosher_deco: "Seauceur chic",
  explosher: "Détoneur",
  explosher_custom: "Détoneur modifié",
  furo: "Bassineur",
  furo_deco: "Bassineur chic",
  hissen: "Dépoteur",
  hissen_ash: "Dépoteur 100-DRÉ",
  hissen_hue: "Dépoteur nuancé",
  moprin: "Seau S-Horreur",
  moprin_d: "Seau S-Horreur Cétacé",
  moprin_kaku: "Seau S-Horreur kérapex",
  order_slosher_replica: "Seau d'Ordre (réplique)",
  screwslosher: "Encrifugeur",
  screwslosher_neo: "Encrifugeur Néo",
  barrelspinner: "Badigeonneur",
  barrelspinner_deco: "Badigeonneur chic",
  examiner: "Correcteur",
  examiner_hue: "Correcteur nuancé",
  hydra: "Exteinteur",
  hydra_atsu: "Exteinteur cascapex",
  hydra_custom: "Exteinteur modifié",
  kugelschreiber: "Badigeonneur stylo",
  kugelschreiber_hue: "Badigeonneur stylo nuancé",
  order_spinner_replica: "Badigeonneur d'Ordre (réplique)",
  splatspinner: "Badigeonneur XS",
  splatspinner_collabo: "Badigeonneur XS griffé",
  splatspinner_pytn: "Badigeonneur XS VN-1",
  brella24mk1: "Para-encre Ré-gen 24 Mk I",
  brella24mk2: "Para-encre Ré-gen 24 Mk II",
  campingshelter: "Para-encre XL",
  campingshelter_crem: "Para-encre XL CRM-A",
  campingshelter_sorella: "Para-encre XL Sorella",
  order_shelter_replica: "Para-encre d'Ordre (réplique)",
  parashelter: "Para-encre",
  parashelter_sorella: "Para-encre Sorella",
  spygadget: "Para-encre espion",
  spygadget_ryo: "Para-encre espion amalgapex",
  spygadget_sorella: "Para-encre espion Sorella",
  furuido: "Multisperceur V",
  furuido_custom: "Multisperceur V modifié",
  lact450: "Coralux 450",
  lact450_deco: "Coralux 450 chic",
  lact450_milk: "Coralux 450 LACTO",
  order_stringer_replica: "Transperceur d'Ordre (réplique)",
  tristringer: "Trisperceur",
  tristringer_collabo: "Trisperceur Abysma",
  tristringer_tou: "Trisperceur prismapex",
};

/** Nom francais d'une arme, ou `undefined` si elle n'est pas dans la table. */
export function nomFrancaisDeLArme(cle: string | undefined): string | undefined {
  return cle === undefined ? undefined : ARMES[cle];
}
